### ISSUE TITLE
Assignment 3-3 - Constructors

### ISSUE THREAD

**Issue by ambethia** [SJGadsden/Assignments#10]
# Constructors
## Description

Copy the included [`constructors.js`](https://raw.githubusercontent.com/tiy-tpa-js-q3-2015/notes/master/week-3/constructors.js) to a new project. Add an `index.html` that includes it. Answer all the questions and upload to **gh-pages**.

Keep in mind in the examples in `constructors.js` I need to be able to test them in **gh-pages** on the console. Also make sure there are no javascript errors and check your code in [js hint](http://jshint.com/). Finally make sure it is formatted/indented correctly. Code is in place that validates each answer. It will currently say: `Assertion failed` for each question. Once you answer the question correctly that will go away. Use this to check your work.
### Learning Objectives

After completing this assignment, you should…
- Understand how constructor functions work in JavaScript
### Performance Objectives

After completing this assignment, you be able to effectively use
- [Github Pages](https://pages.github.com/)
### Deliverables
- A repo containing at least:
  - the `constructors.js` file
  - a branch called `gh-pages`
### Requirements
- No JSHint warnings or errors
## Additional Resources
- [Object.prototype.constructor](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/constructor)
- [Working with objects](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Working_with_Objects)

**Comment by SJGadsden** [comment]
file:///Users/macbookowner/Documents/theironyard/master/week3day3/constructor.js

**Comment by ambethia** [comment]
@SJGadsden That's a link to your local file on your laptop, I need a URL to the code in a repo or on gh-pages, etc so I can check it out. Thanks!

**Comment by ambethia** [comment]
![Awesome Work!](http://media.giphy.com/media/OCv3v7ORwJRSw/200w_d.gif)
