### ISSUE TITLE
Assignment 3-1 - Timeline

### ISSUE THREAD

**Issue by ambethia** [SJGadsden/Assignments#9]
### Description

Recreate the following layout:

![](https://dl.dropboxusercontent.com/u/4024808/tiy/timeline.png)
### Objectives
- Understand SASS/SCSS and Jade Preprocessors
- Understand Flexbox
- Understand the Gulp build system
### Deliverables
- [ ] a git repo containing `sass` and `jade` files.
- [ ] a working, publicly visible website with a public URL (i.e. on Github Pages).
## Explorer Mode
- [ ] If you haven't already, watch this video series: [What the Flexbox?!](https://www.youtube.com/watch?v=Vj7NZ6FiQvo&list=PLu8EoSxDXHP7xj_y6NIAhy0wuCd4uVdid)
- [ ] Use `gulp` to automate the processing of your source files
- [ ] Use `SCSS/SASS` to author your stylesheets
- [ ] Use `Jade` to author your `HTML` documents
- [ ] Use `flexbox` in your stylesheets to layout the elements
- [ ] Use `@media` queries to handle a responsive layout

Feel free to refer to the [`Gulpfile.js`](https://github.com/tiy-tpa-js-q3-2015/notes/blob/master/week-3/day-1-class/paws-of-love/gulpfile.js) we did in class today.
## Adventure Mode
- [ ] Use Gulp to automate creating and updating a `gh-pages` branch that contains just your publishable documents (the generated `html` and `css`). _**hint**: Check the Additional Resources for something that might help with this!_
## Additional Resources & Documenation
- http://sass-lang.com
- http://jade-lang.com
- http://gulpjs.com
- https://css-tricks.com/snippets/css/a-guide-to-flexbox/
- https://www.npmjs.com/package/gulp-gh-pages

**Comment by SJGadsden** [comment]
http://codepen.io/SJGadsden/pen/yYayrp

**Comment by ambethia** [comment]
![Awesome Work!](http://media.giphy.com/media/5fBH6zrcIiOs65zXCtG/200w_d.gif)
